### ISSUE TITLE
New page design for Critical Studies

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#56]
Apparently they are upset that it doesn't look like their page in the print catalog. We now have the attached reference (which is also the first I've seen of it).

@bjornmeansbear, do you want to take this one? Or are you still bogged down with your other project and want @nourtabet or me to handle it?

E

**Comment by emmasf** [comment]
(pdf did not attach)

... we can ignore the folio details and such, I think we just need to handle the main section.
![Uploading criticalstudiesMA_proof_v2.jpg . . .]()

**Comment by bjornmeansbear** [comment]
The layout didn't attach?
If you guys can handle it I'd be much obliged — wrapping up the other site still

**Comment by emmasf** [comment]
I can handle it after Monday.

**Comment by nourtabet** [comment]
Bryan Hempel is still there

**Comment by bjornmeansbear** [comment]
I added him to list of people to omit. Next update he'll be gone.

**Comment by emmasf** [comment]
HEMPELLLLLLLLLL

**Comment by nourtabet** [comment]
#hempelwillalwaysfindyou

**Comment by bjornmeansbear** [comment]
I am afraid.

**Comment by nourtabet** [comment]
i worked the page/added the content that should be there
the styling is not terrific. 
the title of this one dude is super long and i didn't know which class to use and still make it successfully responsive.
ill look into that mid next week.

**Comment by bjornmeansbear** [comment]
This looks better. I still don't know what its supposed to look like, but what issues were you running into class-wise @nourtabet ?

**Comment by nourtabet** [comment]
Zachary Franklin's descriptions is super long.
the class is <div class="col-xs-9">
when i make it 7 it looks better, breaking down the line, but the column becomes super tight on mobile.

i can look into it later this week and figure it out.

**Comment by emmasf** [comment]
Want to sit tonight and look at this? Let me know.

**Comment by bjornmeansbear** [comment]
I think I fixed this — what do you guys think?
I don't see anything wrong with long titles wrapping lines... that's life

also, when <tagging>, <b> does mean bold, but its meant as a last resort if
there is no other more meaningful tag that can be used. In a semantic
listing like this peoples' names could be <h#> tags, or it is at least
preferable to use <strong> instead of <b> ... of course, this are just made
up rules by the whomever thinks about these things... but <b> and <i> are
really only meant to be used if there is no semantic meaning to bolding or
italicizing... (for example, the title of a book should be wrapped in
<cite> tags, not just <i>s)

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kristian.bjornard@gmail.com
w:   kristian.bjornard.com
w:   thesustainabilitist.com
twitter: @bjornmeansbear

**Comment by bjornmeansbear** [comment]
I'm going to mark this done, unless there is something else required for it @nourtabet or @emmasf ?

**Comment by emmasf** [comment]
Done and done. 

Typed on a phone, please excuse brevity.
